# This is a script to run SVM on the yelp data for a baseline test. We run multiple
# SVM Classifiers for multiple C values and both linear and polynomial clasifiers.
# The results of the test are outputted to text fles.

from __future__ import print_function
import numpy as np
from sklearn import svm
from sklearn import metrics, datasets
import baseline_loader_average
import baseline_loader_middle
import baseline_loader_all
import decimal

__author__ = 'jasonfeng'

(avg_training_data, avg_test_data, avg_training_labels, avg_testing_labels) = baseline_loader_average.load_data()

print("Average Classifier Started")
avg_classifer = svm.SVC(probability=True)
avg_classifer.fit(avg_training_data, avg_training_labels)
avg_classifer_score = avg_classifer.score(avg_training_data, avg_training_labels)
avg_predictions = (avg_classifer.predict(avg_test_data))
avg_probs = avg_classifer.predict_proba(avg_test_data)
avg_test_error =  metrics.accuracy_score(avg_testing_labels, avg_predictions)
print("Average Classifier Finished")

print("Average Linear SVM C=0.1 Started")
avg_linear_svc_01 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=0.1)
avg_linear_svc_01.fit(avg_training_data, avg_training_labels)
avg_linear_score_01 = avg_linear_svc_01.score(avg_training_data, avg_training_labels)
avg_linear_predictions_01 = (avg_linear_svc_01.predict(avg_test_data))
avg_linear_probs_01 = avg_linear_svc_01.predict_proba(avg_test_data)
avg_linear_test_error_01 =  metrics.accuracy_score(avg_testing_labels, avg_predictions)
print("Average Linear SVM C=0.1 Finished")

print("Average Linear SVM C=1 Started")
avg_linear_svc_1 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=1.)
avg_linear_svc_1.fit(avg_training_data, avg_training_labels)
avg_linear_score_1 = avg_linear_svc_1.score(avg_training_data, avg_training_labels)
avg_linear_predictions_1 = (avg_linear_svc_1.predict(avg_test_data))
avg_linear_probs_1 = avg_linear_svc_1.predict_proba(avg_test_data)
avg_linear_test_error_1 =  metrics.accuracy_score(avg_testing_labels, avg_predictions)
print("Average Linear SVM C=1 Finished")

print("Average Linear SVM C=10 Started")
avg_linear_svc_10 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=10.)
avg_linear_svc_10.fit(avg_training_data, avg_training_labels)
avg_linear_score_10 = avg_linear_svc_10.score(avg_training_data, avg_training_labels)
avg_linear_predictions_10 = (avg_linear_svc_10.predict(avg_test_data))
avg_linear_probs_10 = avg_linear_svc_10.predict_proba(avg_test_data)
avg_linear_test_error_10 =  metrics.accuracy_score(avg_testing_labels, avg_predictions)
print("Average Linear SVM C=10 Finished")

print("Average Linear SVM C=100 Started")
avg_linear_svc_100 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=100.)
avg_linear_svc_100.fit(avg_training_data, avg_training_labels)
avg_linear_score_100 = avg_linear_svc_100.score(avg_training_data, avg_training_labels)
avg_linear_predictions_101 = (avg_linear_svc_100.predict(avg_test_data))
avg_linear_probs_101 = avg_linear_svc_100.predict_proba(avg_test_data)
avg_linear_test_error_100 =  metrics.accuracy_score(avg_testing_labels, avg_predictions)
print("Average Linear SVM C=100 Finished")

print("Average Poly SVM Started")
avg_poly_svc = svm.SVC(kernel='poly', degree=3, probability=True)
avg_poly_svc.fit(avg_training_data, avg_training_labels)
avg_poly_score = avg_poly_svc.score(avg_training_data, avg_training_labels)
avg_poly_predictions = (avg_poly_svc.predict(avg_test_data))
avg_poly_probs = avg_poly_svc.predict_proba(avg_test_data)
avg_poly_error =  metrics.accuracy_score(avg_testing_labels, avg_poly_predictions)
print("Average Poly SVM Finished")

f = open('svm_results_avg','w')
f.write("Avg Classifer training error: " + str(avg_classifer_score) + '\n')
f.write("Avg Classifer test error: " + str(avg_test_error) + '\n')
f.write("Avg Linear training error C = 0.1: " + str(avg_linear_score_01) + '\n')
f.write("Avg Linear test error C = 0.1: " + str(avg_linear_test_error_01) + '\n')
f.write("Avg Linear training error C = 1: " + str(avg_linear_score_1) + '\n')
f.write("Avg Linear test error C = 1: " + str(avg_linear_test_error_1) + '\n')
f.write("Avg Linear training error C = 10: " + str(avg_linear_score_10) + '\n')
f.write("Avg Linear test error C = 10: " + str(avg_linear_test_error_10) + '\n')
f.write("Avg Linear training error C = 100: " + str(avg_linear_score_100) + '\n')
f.write("Avg Linear test error C = 100: " + str(avg_linear_test_error_100) + '\n')
f.write("Avg Poly training error: " + str(avg_poly_score) + '\n')
f.write("Avg Poly test error: " + str(avg_poly_error) + '\n')
f.close()

(mid_training_data, mid_test_data, mid_training_labels, mid_testing_labels) = baseline_loader_middle.load_data()

print("Middle Classifier Started")
mid_classifer = svm.SVC(probability=True)
mid_classifer.fit(mid_training_data, mid_training_labels)
mid_classifer_score = mid_classifer.score(mid_training_data, mid_training_labels)
mid_predictions = (mid_classifer.predict(mid_test_data))
mid_probs = mid_classifer.predict_proba(mid_test_data)
mid_test_error =  metrics.accuracy_score(mid_testing_labels, mid_predictions)
print("Middle Classifier Finished")

print("Middle Linear SVM C=0.1 Started")
mid_linear_svc_01 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=0.1)
mid_linear_svc_01.fit(mid_training_data, mid_training_labels)
mid_linear_score_01 = mid_linear_svc_01.score(mid_training_data, mid_training_labels)
mid_linear_predictions_01 = (mid_linear_svc_01.predict(mid_test_data))
mid_linear_probs_01 = mid_linear_svc_01.predict_proba(mid_test_data)
mid_linear_test_error_01 =  metrics.accuracy_score(mid_testing_labels, mid_predictions)
print("Middle Linear SVM C=0.1 Finished")

print("Middle Linear SVM C=1 Started")
mid_linear_svc_1 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=1.)
mid_linear_svc_1.fit(mid_training_data, mid_training_labels)
mid_linear_score_1 = mid_linear_svc_1.score(mid_training_data, mid_training_labels)
mid_linear_predictions_1 = (mid_linear_svc_1.predict(mid_test_data))
mid_linear_probs_1 = mid_linear_svc_1.predict_proba(mid_test_data)
mid_linear_test_error_1 =  metrics.accuracy_score(mid_testing_labels, mid_predictions)
print("Middle Linear SVM C=1 Finished")

print("Middle Linear SVM C=10 Started")
mid_linear_svc_10 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=10.)
mid_linear_svc_10.fit(mid_training_data, mid_training_labels)
mid_linear_score_10 = mid_linear_svc_10.score(mid_training_data, mid_training_labels)
mid_linear_predictions_10 = (mid_linear_svc_10.predict(mid_test_data))
mid_linear_probs_10 = mid_linear_svc_10.predict_proba(mid_test_data)
mid_linear_test_error_10 =  metrics.accuracy_score(mid_testing_labels, mid_predictions)
print("Middle Linear SVM C=10 Finished")

print("Middle Linear SVM C=100 Started")
mid_linear_svc_100 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=100.)
mid_linear_svc_100.fit(mid_training_data, mid_training_labels)
mid_linear_score_100 = mid_linear_svc_100.score(mid_training_data, mid_training_labels)
mid_linear_predictions_101 = (mid_linear_svc_100.predict(mid_test_data))
mid_linear_probs_101 = mid_linear_svc_100.predict_proba(mid_test_data)
mid_linear_test_error_100 =  metrics.accuracy_score(mid_testing_labels, mid_predictions)
print("Middle Linear SVM C=100 Finished")

print("Middle Poly SVM Started")
mid_poly_svc = svm.SVC(kernel='poly', degree=3, probability=True)
mid_poly_svc.fit(mid_training_data, mid_training_labels)
mid_poly_score = mid_poly_svc.score(mid_training_data, mid_training_labels)
mid_poly_predictions = (mid_poly_svc.predict(mid_test_data))
mid_poly_probs = mid_poly_svc.predict_proba(mid_test_data)
mid_poly_error =  metrics.accuracy_score(mid_testing_labels, mid_poly_predictions)
print("Middle Poly SVM Finished")

f = open('svm_results_mid','w')

f.write("Mid Classifer training error: " + str(mid_classifer_score) + '\n')
f.write("Mid Classifer test error: " + str(mid_test_error) + '\n')
f.write("Mid Linear training error C = 0.1: " + str(mid_linear_score_01) + '\n')
f.write("Mid Linear test error C = 0.1: " + str(mid_linear_test_error_01) + '\n')
f.write("Mid Linear training error C = 1: " + str(mid_linear_score_1) + '\n')
f.write("Mid Linear test error C = 1: " + str(mid_linear_test_error_1) + '\n')
f.write("Mid Linear training error C = 10: " + str(mid_linear_score_10) + '\n')
f.write("Mid Linear test error C = 10: " + str(mid_linear_test_error_10) + '\n')
f.write("Mid Linear training error C = 100: " + str(mid_linear_score_100) + '\n')
f.write("Mid Linear test error C = 100: " + str(mid_linear_test_error_100) + '\n')
f.write("Mid Poly training error: " + str(mid_poly_score) + '\n')
f.write("Mid Poly test error: " + str(mid_poly_error) + '\n')
f.close()

(all_training_data, all_test_data, all_training_labels, all_testing_labels) = import baseline_loader_all.load_data()

print("All Features Classifier Started")
all_classifer = svm.SVC(probability=True)
all_classifer.fit(all_training_data, all_training_labels)
all_classifer_score = all_classifer.score(all_training_data, all_training_labels)
all_predictions = (all_classifer.predict(all_test_data))
all_probs = all_classifer.predict_proba(all_test_data)
avg_test_error =  metrics.accuracy_score(all_testing_labels, all_predictions)
print("All Features Classifier Finished")

print("All Features Linear SVM C=0.1 Started")
all_linear_svc_01 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=0.1)
all_linear_svc_01.fit(all_training_data, all_training_labels)
all_linear_score_01 = all_linear_svc_01.score(all_training_data, all_training_labels)
all_linear_predictions_01 = (all_linear_svc_01.predict(all_test_data))
all_linear_probs_01 = all_linear_svc_01.predict_proba(all_test_data)
all_linear_test_error_01 =  metrics.accuracy_score(all_testing_labels, all_predictions)
print("All Features Linear SVM C=0.1 Finished")

print("All Features Linear SVM C=1 Started")
all_linear_svc_1 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=1.)
all_linear_svc_1.fit(all_training_data, all_training_labels)
all_linear_score_1 = all_linear_svc_1.score(all_training_data, all_training_labels)
all_linear_predictions_1 = (all_linear_svc_1.predict(all_test_data))
all_linear_probs_1 = all_linear_svc_1.predict_proba(all_test_data)
all_linear_test_error_1 =  metrics.accuracy_score(all_testing_labels, all_predictions)
print("All Features Linear SVM C=1 Finished")

print("All Features Linear SVM C=10 Started")
all_linear_svc_10 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=10.)
all_linear_svc_10.fit(all_training_data, all_training_labels)
all_linear_score_10 = all_linear_svc_10.score(all_training_data, all_training_labels)
all_linear_predictions_10 = (all_linear_svc_10.predict(all_test_data))
all_linear_probs_10 = all_linear_svc_10.predict_proba(all_test_data)
all_linear_test_error_10 =  metrics.accuracy_score(all_testing_labels, all_predictions)
print("All Features Linear SVM C=10 Finished")

print("All Features Linear SVM C=100 Started")
all_linear_svc_100 = svm.SVC(kernel='linear', probability=True, gamma=0.001, C=100.)
all_linear_svc_100.fit(all_training_data, all_training_labels)
all_linear_score_100 = all_linear_svc_100.score(all_training_data, all_training_labels)
all_linear_predictions_101 = (all_linear_svc_100.predict(all_test_data))
all_linear_probs_101 = all_linear_svc_100.predict_proba(all_test_data)
all_linear_test_error_100 =  metrics.accuracy_score(all_testing_labels, all_predictions)
print("All Features Linear SVM C=100 Finished")

print("All Features Poly SVM Started")
all_poly_svc = svm.SVC(kernel='poly', degree=3, probability=True)
all_poly_svc.fit(all_training_data, all_training_labels)
all_poly_score = all_poly_svc.score(all_training_data, all_training_labels)
all_poly_predictions = (all_poly_svc.predict(all_test_data))
all_poly_probs = all_poly_svc.predict_proba(all_test_data)
all_poly_error =  metrics.accuracy_score(all_testing_labels, all_poly_predictions)
print("All Features Poly SVM Finished")

f = open('svm_results_all','w')
f.write("All Features Classifer training error: " + str(all_classifer_score) + '\n')
f.write("All Features Classifer test error: " + str(avg_test_error) + '\n')
f.write("All Features Linear training error C = 0.1: " + str(all_linear_score_01) + '\n')
f.write("All Features Linear test error C = 0.1: " + str(all_linear_test_error_01) + '\n')
f.write("All Features Linear training error C = 1: " + str(all_linear_score_1) + '\n')
f.write("All Features Linear test error C = 1: " + str(all_linear_test_error_1) + '\n')
f.write("All Features Linear training error C = 10: " + str(all_linear_score_10) + '\n')
f.write("All Features Linear test error C = 10: " + str(all_linear_test_error_10) + '\n')
f.write("All Features Linear training error C = 100: " + str(all_linear_score_100) + '\n')
f.write("All Features Linear test error C = 100: " + str(all_linear_test_error_100) + '\n')
f.write("All Features Poly training error: " + str(all_poly_score) + '\n')
f.write("All Features Poly test error: " + str(all_poly_error) + '\n')
f.close()